server:
  port: 8090
  environment: dev
  bodyLimit: 10
  timeout: 30
  client_url: "http://localhost:3001,http://localhost:8080,http://localhost:5173"
  server_domain: "localhost"

database:
  driver: postgres
  host: localhost
  port: 8080
  user: postgres
  password: ""
  dbname: ai_marketing
  sslmode: disable
  schema: public

env:
  secretkey: ""
